### ISSUE TITLE
Variable Ranges

### ISSUE THREAD

**Issue by AndreLobato** [metocean/api-conventions#6]
Should we use the same sintax for variable values ranges then we use for time?

hs=1--4 
hs=--4
hs=4--

this means for negative values:

level=-3---3

does this seems all right? maybe bug prone?

**Comment by AndreLobato** [comment]
I would like to suggest to use ~ (tilde) for indication of time range. Mostly because it's actually the only URL-safe character which is not being used to anything else, I find a improvement against `--` bacuse...
1) It's only 1 char (less error prone)
2) differentiates when using negatives values (more explicit)
3) Looks nicer, exemple:

`time=2015-05-03~2016-03-12`

`time=2015-05-03--2016-03-12`

**Comment by aportagain** [comment]
I agree with 1. and especially 2., not sure about 3. (I think for me personally, the wider horizontal separation of the two characters is actually easier to read / find). But to be honest I think we should stick with the double hyphen `--` simply because it doesn't violate ISO8601 (section "4.4.2 Separators and designators" first mentions a slash / solidus `/`, but then later says "In certain application areas a double hyphen is used as a separator instead of a solidus"). So if we stick to the double hyphen it's much more likely that clients can use existing parsers and in some cases maybe even generators for those time range / interval strings.

**Comment by JBoudMS** [comment]
Anecdotally, we use `-PT30M---PT15M` in our configuration in places (which then gets translated to something like `2015-05-03T03:00:00.000Z--2016-05-03T03:15:00.000Z`).

You get used to reading it, but it can be error-prone at first. I think it depends on how experienced you expect users to be. They will find `---` and `--` hard to distinguish at first, and it means when they're bug hunting they may not notice the subtle bug at first.

Personally, I don't like the idea of not sticking to the ISO-8601 spec, but I understand that negative values and `--` is frustrating and `/` is annoyingly not URL-safe.

I would suggest that if you're going to support `~` you still continue support for `--`, for both times and variables. Not supporting `--` in times would break a lot of clients, and supporting both means that clients that expect standard things like `2015-05-03T03:00:00.000Z--PT15M` to work aren't surprised, but those that want things easier to read, can do so. Not supporting it means that any libraries that give out standard ISO-8601 time intervals will have to have their output transformed.

**Comment by AndreLobato** [comment]
After hearing opinions I don't think is worth to come with a new standard for that. Closing that.
